# Generated by Django 2.0.8 on 2018-08-13 15:15

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180813_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='slide_content_1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='slide_content_2',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='slide_content_3',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
